# Scaleway configuration file
access_key: EXAMPLESCW34P0XKFD4
secret_key: example-2b41-8d52-f888-8c8a460e
default_organization_id: example-468g-4f65-a41e-8b40766c5fc5
default_project_id: example-468g-4f65-a41e-8b40766c5fc5
default_zone: fr-par-1
default_region: fr-par
api_url: https://api.scaleway.com